Linux kernel: leancrypto_kernel_rng_tester: include linux/hex.h
Since commit 24c776355f40 ("kernel.h: drop hex.h and update all hex.h
users"), hex.h is not included from kernel.h. It needs to be included in
each file using the functions. That is the case in
leancrypto_kernel_rng_tester:
 ../drng/tests/leancrypto_kernel_rng_tester.c: In function ‘lc_seeded_rng_test’:
 ../drng/tests/leancrypto_kernel_rng_tester.c:43:9: error: implicit declaration of function ‘bin2hex’ [-Wimplicit-function-declaration]
    43 |         bin2hex(hex, outbuf, sizeof(outbuf));
       |         ^~~~~~~