meson: make it build without ascon and ascon_keccak features
Previously, when configured with -Dascon=disabled
-Dascon_keccak=disabled, the build failed with:

  /usr/bin/ld: /tmp/cceQTV28.ltrans0.ltrans.o: warning: relocation against `lc_ascon_aead' in read-only section `.text'
  /usr/bin/ld: /tmp/cceQTV28.ltrans0.ltrans.o: in function `ak_tester_one.constprop.0':
  /home/ueno/devel/leancrypto/build/../aead/tests/ascon_crypt_wrong_algo.c:36:(.text+0x103): undefined reference to `lc_ascon_aead'
  /usr/bin/ld: warning: creating DT_TEXTREL in a PIE
collect2: error: ld returned 1 exit status

This fixes it by adding a missing check on ascon_keccak in the
meson.build file as well as move the ascon_crypt_wrong_algo test under
the get_option('ascon').enabled() condition.

Signed-off-by: Daiki Ueno <dueno@redhat.com>